server:
  port: 8666
  address: 127.0.0.1
#  address: 0.0.0.0

  shutdown: graceful
  max-http-request-header-size: 16KB

  ssl:
    enabled: false
#    key-store: /Users/kees/Code/rds/rds-platform.p12
#    key-store-password: rdsrds
#    key-store-type: PKCS12
#    key-alias: rds-platform

  jetty:
    threads:
      min: 10
      max: 200
      idle-timeout: 60000

    accesslog:
      enabled: true
      directory: /opt/rds/log
      filename: access.log
      file-date-format: .yyyy-MM-dd
      retention-period: 30
      append: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rdsdb
    username: rds
    password: rds
#    password: strongpassword
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  jwt:
    secret: dGhpcyBpcyBhIHZlcnkgc2VjdXJlIGtleSBmb3IgSldUIHNpZ25pbmcgMjU2Yml0
#    1 uur
    expiration-ms: 3600000
#    1 uur
    booker-expiration-ms: 3600000
  otp:
    expiry-minutes: 10
    max-active-per-email: 3

  mollie:
    api:
      payments:
        base: https://api.mollie.com/v2/payments
    key: Bearer test_GpPHhs7SHk73fAyMyaJUFUKJQdxDD5
    urls:
      webhook: http://217.63.23.31:8082/api/mollie/payments/webhook
      redirect: http://178.104.163.88:5003/payments
#      webhook: http://178.104.163.88/api/mollie/payments/webhook
#      redirect: https://rds.kbtg/booker/payments
